//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYS_SGI.Presentation.ServiceSecurity {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OpcionLogic", Namespace="http://schemas.datacontract.org/2004/07/SYS_SECURITY.Domain.Implementation.Logica" +
        "lEntities.SEG")]
    [System.SerializableAttribute()]
    public partial class OpcionLogic : SYS_SGI.Presentation.ServiceSecurity.Opcion {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantTotalRegistrosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoAccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float CodigoSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ControladorModuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GlyphiconModuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SYS_SGI.Presentation.ServiceSecurity.InfoMovs InfoMovsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetodoModuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpcionPadreDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaImagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SistemaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantTotalRegistros {
            get {
                return this.CantTotalRegistrosField;
            }
            set {
                if ((this.CantTotalRegistrosField.Equals(value) != true)) {
                    this.CantTotalRegistrosField = value;
                    this.RaisePropertyChanged("CantTotalRegistros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoAccion {
            get {
                return this.CodigoAccionField;
            }
            set {
                if ((this.CodigoAccionField.Equals(value) != true)) {
                    this.CodigoAccionField = value;
                    this.RaisePropertyChanged("CodigoAccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoPerfil {
            get {
                return this.CodigoPerfilField;
            }
            set {
                if ((this.CodigoPerfilField.Equals(value) != true)) {
                    this.CodigoPerfilField = value;
                    this.RaisePropertyChanged("CodigoPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float CodigoSistema {
            get {
                return this.CodigoSistemaField;
            }
            set {
                if ((this.CodigoSistemaField.Equals(value) != true)) {
                    this.CodigoSistemaField = value;
                    this.RaisePropertyChanged("CodigoSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ControladorModulo {
            get {
                return this.ControladorModuloField;
            }
            set {
                if ((object.ReferenceEquals(this.ControladorModuloField, value) != true)) {
                    this.ControladorModuloField = value;
                    this.RaisePropertyChanged("ControladorModulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GlyphiconModulo {
            get {
                return this.GlyphiconModuloField;
            }
            set {
                if ((object.ReferenceEquals(this.GlyphiconModuloField, value) != true)) {
                    this.GlyphiconModuloField = value;
                    this.RaisePropertyChanged("GlyphiconModulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SYS_SGI.Presentation.ServiceSecurity.InfoMovs InfoMovs {
            get {
                return this.InfoMovsField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoMovsField, value) != true)) {
                    this.InfoMovsField = value;
                    this.RaisePropertyChanged("InfoMovs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetodoModulo {
            get {
                return this.MetodoModuloField;
            }
            set {
                if ((object.ReferenceEquals(this.MetodoModuloField, value) != true)) {
                    this.MetodoModuloField = value;
                    this.RaisePropertyChanged("MetodoModulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modulo {
            get {
                return this.ModuloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModuloField, value) != true)) {
                    this.ModuloField = value;
                    this.RaisePropertyChanged("Modulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OpcionPadreDesc {
            get {
                return this.OpcionPadreDescField;
            }
            set {
                if ((object.ReferenceEquals(this.OpcionPadreDescField, value) != true)) {
                    this.OpcionPadreDescField = value;
                    this.RaisePropertyChanged("OpcionPadreDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Perfil {
            get {
                return this.PerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.PerfilField, value) != true)) {
                    this.PerfilField = value;
                    this.RaisePropertyChanged("Perfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutaImagen {
            get {
                return this.RutaImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaImagenField, value) != true)) {
                    this.RutaImagenField = value;
                    this.RaisePropertyChanged("RutaImagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sistema {
            get {
                return this.SistemaField;
            }
            set {
                if ((object.ReferenceEquals(this.SistemaField, value) != true)) {
                    this.SistemaField = value;
                    this.RaisePropertyChanged("Sistema");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Audity", Namespace="http://schemas.datacontract.org/2004/07/SYS_SECURITY.Domain.Implementation.Entiti" +
        "es.BASE")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SYS_SGI.Presentation.ServiceSecurity.Usuarios))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SYS_SGI.Presentation.ServiceSecurity.UsuariosLogic))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SYS_SGI.Presentation.ServiceSecurity.Sistema))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SYS_SGI.Presentation.ServiceSecurity.SistemaLogic))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SYS_SGI.Presentation.ServiceSecurity.Empresa))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SYS_SGI.Presentation.ServiceSecurity.EmpresaLogic))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SYS_SGI.Presentation.ServiceSecurity.Opcion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SYS_SGI.Presentation.ServiceSecurity.OpcionLogic))]
    public partial class Audity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TerminalCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TerminalModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string terminalCreacion1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string terminalModificacion1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TerminalCreacion {
            get {
                return this.TerminalCreacionField;
            }
            set {
                if ((object.ReferenceEquals(this.TerminalCreacionField, value) != true)) {
                    this.TerminalCreacionField = value;
                    this.RaisePropertyChanged("TerminalCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TerminalModificacion {
            get {
                return this.TerminalModificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.TerminalModificacionField, value) != true)) {
                    this.TerminalModificacionField = value;
                    this.RaisePropertyChanged("TerminalModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioCreacion {
            get {
                return this.UsuarioCreacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioCreacionField, value) != true)) {
                    this.UsuarioCreacionField = value;
                    this.RaisePropertyChanged("UsuarioCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioModificacion {
            get {
                return this.UsuarioModificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioModificacionField, value) != true)) {
                    this.UsuarioModificacionField = value;
                    this.RaisePropertyChanged("UsuarioModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="terminalCreacion")]
        public string terminalCreacion1 {
            get {
                return this.terminalCreacion1Field;
            }
            set {
                if ((object.ReferenceEquals(this.terminalCreacion1Field, value) != true)) {
                    this.terminalCreacion1Field = value;
                    this.RaisePropertyChanged("terminalCreacion1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="terminalModificacion")]
        public string terminalModificacion1 {
            get {
                return this.terminalModificacion1Field;
            }
            set {
                if ((object.ReferenceEquals(this.terminalModificacion1Field, value) != true)) {
                    this.terminalModificacion1Field = value;
                    this.RaisePropertyChanged("terminalModificacion1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuarios", Namespace="http://schemas.datacontract.org/2004/07/SYS_SECURITY.Domain.Implementation.Entiti" +
        "es.SEG")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SYS_SGI.Presentation.ServiceSecurity.UsuariosLogic))]
    public partial class Usuarios : SYS_SGI.Presentation.ServiceSecurity.Audity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CodigoCargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CodigoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DominioRedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumDocumentoIdentidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TipoDocumentoIdentidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CodigoCargo {
            get {
                return this.CodigoCargoField;
            }
            set {
                if ((this.CodigoCargoField.Equals(value) != true)) {
                    this.CodigoCargoField = value;
                    this.RaisePropertyChanged("CodigoCargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPersona {
            get {
                return this.CodigoPersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPersonaField, value) != true)) {
                    this.CodigoPersonaField = value;
                    this.RaisePropertyChanged("CodigoPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CodigoUsuario {
            get {
                return this.CodigoUsuarioField;
            }
            set {
                if ((this.CodigoUsuarioField.Equals(value) != true)) {
                    this.CodigoUsuarioField = value;
                    this.RaisePropertyChanged("CodigoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasena {
            get {
                return this.ContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasenaField, value) != true)) {
                    this.ContrasenaField = value;
                    this.RaisePropertyChanged("Contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DominioRed {
            get {
                return this.DominioRedField;
            }
            set {
                if ((object.ReferenceEquals(this.DominioRedField, value) != true)) {
                    this.DominioRedField = value;
                    this.RaisePropertyChanged("DominioRed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumDocumentoIdentidad {
            get {
                return this.NumDocumentoIdentidadField;
            }
            set {
                if ((object.ReferenceEquals(this.NumDocumentoIdentidadField, value) != true)) {
                    this.NumDocumentoIdentidadField = value;
                    this.RaisePropertyChanged("NumDocumentoIdentidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TipoDocumentoIdentidad {
            get {
                return this.TipoDocumentoIdentidadField;
            }
            set {
                if ((this.TipoDocumentoIdentidadField.Equals(value) != true)) {
                    this.TipoDocumentoIdentidadField = value;
                    this.RaisePropertyChanged("TipoDocumentoIdentidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuariosLogic", Namespace="http://schemas.datacontract.org/2004/07/SYS_SECURITY.Domain.Implementation.Logica" +
        "lEntities.SEG")]
    [System.SerializableAttribute()]
    public partial class UsuariosLogic : SYS_SGI.Presentation.ServiceSecurity.Usuarios {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantTotalRegistrosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SYS_SGI.Presentation.ServiceSecurity.InfoMovs InfoMovsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCompletoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ReestablecerContrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantTotalRegistros {
            get {
                return this.CantTotalRegistrosField;
            }
            set {
                if ((this.CantTotalRegistrosField.Equals(value) != true)) {
                    this.CantTotalRegistrosField = value;
                    this.RaisePropertyChanged("CantTotalRegistros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cargo {
            get {
                return this.CargoField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoField, value) != true)) {
                    this.CargoField = value;
                    this.RaisePropertyChanged("Cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SYS_SGI.Presentation.ServiceSecurity.InfoMovs InfoMovs {
            get {
                return this.InfoMovsField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoMovsField, value) != true)) {
                    this.InfoMovsField = value;
                    this.RaisePropertyChanged("InfoMovs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCompleto {
            get {
                return this.NombreCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCompletoField, value) != true)) {
                    this.NombreCompletoField = value;
                    this.RaisePropertyChanged("NombreCompleto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReestablecerContrasena {
            get {
                return this.ReestablecerContrasenaField;
            }
            set {
                if ((this.ReestablecerContrasenaField.Equals(value) != true)) {
                    this.ReestablecerContrasenaField = value;
                    this.RaisePropertyChanged("ReestablecerContrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sistema", Namespace="http://schemas.datacontract.org/2004/07/SYS_SECURITY.Domain.Implementation.Entiti" +
        "es.SEG")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SYS_SGI.Presentation.ServiceSecurity.SistemaLogic))]
    public partial class Sistema : SYS_SGI.Presentation.ServiceSecurity.Audity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CodigoEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CodigoSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParametroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValorParametroField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CodigoEmpresa {
            get {
                return this.CodigoEmpresaField;
            }
            set {
                if ((this.CodigoEmpresaField.Equals(value) != true)) {
                    this.CodigoEmpresaField = value;
                    this.RaisePropertyChanged("CodigoEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CodigoSistema {
            get {
                return this.CodigoSistemaField;
            }
            set {
                if ((this.CodigoSistemaField.Equals(value) != true)) {
                    this.CodigoSistemaField = value;
                    this.RaisePropertyChanged("CodigoSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Parametro {
            get {
                return this.ParametroField;
            }
            set {
                if ((this.ParametroField.Equals(value) != true)) {
                    this.ParametroField = value;
                    this.RaisePropertyChanged("Parametro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ruta {
            get {
                return this.RutaField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaField, value) != true)) {
                    this.RutaField = value;
                    this.RaisePropertyChanged("Ruta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ValorParametro {
            get {
                return this.ValorParametroField;
            }
            set {
                if ((this.ValorParametroField.Equals(value) != true)) {
                    this.ValorParametroField = value;
                    this.RaisePropertyChanged("ValorParametro");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SistemaLogic", Namespace="http://schemas.datacontract.org/2004/07/SYS_SECURITY.Domain.Implementation.Logica" +
        "lEntities.SEG")]
    [System.SerializableAttribute()]
    public partial class SistemaLogic : SYS_SGI.Presentation.ServiceSecurity.Sistema {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantTotalRegistrosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SYS_SGI.Presentation.ServiceSecurity.InfoMovs InfoMovsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantTotalRegistros {
            get {
                return this.CantTotalRegistrosField;
            }
            set {
                if ((this.CantTotalRegistrosField.Equals(value) != true)) {
                    this.CantTotalRegistrosField = value;
                    this.RaisePropertyChanged("CantTotalRegistros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Empresa {
            get {
                return this.EmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresaField, value) != true)) {
                    this.EmpresaField = value;
                    this.RaisePropertyChanged("Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SYS_SGI.Presentation.ServiceSecurity.InfoMovs InfoMovs {
            get {
                return this.InfoMovsField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoMovsField, value) != true)) {
                    this.InfoMovsField = value;
                    this.RaisePropertyChanged("InfoMovs");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empresa", Namespace="http://schemas.datacontract.org/2004/07/SYS_SECURITY.Domain.Implementation.Entiti" +
        "es.SEG")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SYS_SGI.Presentation.ServiceSecurity.EmpresaLogic))]
    public partial class Empresa : SYS_SGI.Presentation.ServiceSecurity.Audity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float CodigoEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoIdentificadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaImagenLogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaImagenLogoMiniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alias {
            get {
                return this.AliasField;
            }
            set {
                if ((object.ReferenceEquals(this.AliasField, value) != true)) {
                    this.AliasField = value;
                    this.RaisePropertyChanged("Alias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float CodigoEmpresa {
            get {
                return this.CodigoEmpresaField;
            }
            set {
                if ((this.CodigoEmpresaField.Equals(value) != true)) {
                    this.CodigoEmpresaField = value;
                    this.RaisePropertyChanged("CodigoEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoIdentificador {
            get {
                return this.CodigoIdentificadorField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoIdentificadorField, value) != true)) {
                    this.CodigoIdentificadorField = value;
                    this.RaisePropertyChanged("CodigoIdentificador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ruc {
            get {
                return this.RucField;
            }
            set {
                if ((object.ReferenceEquals(this.RucField, value) != true)) {
                    this.RucField = value;
                    this.RaisePropertyChanged("Ruc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutaImagenLogo {
            get {
                return this.RutaImagenLogoField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaImagenLogoField, value) != true)) {
                    this.RutaImagenLogoField = value;
                    this.RaisePropertyChanged("RutaImagenLogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutaImagenLogoMini {
            get {
                return this.RutaImagenLogoMiniField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaImagenLogoMiniField, value) != true)) {
                    this.RutaImagenLogoMiniField = value;
                    this.RaisePropertyChanged("RutaImagenLogoMini");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpresaLogic", Namespace="http://schemas.datacontract.org/2004/07/SYS_SECURITY.Domain.Implementation.Logica" +
        "lEntities.SEG")]
    [System.SerializableAttribute()]
    public partial class EmpresaLogic : SYS_SGI.Presentation.ServiceSecurity.Empresa {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantTotalRegistrosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SYS_SGI.Presentation.ServiceSecurity.InfoMovs InfoMovsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantTotalRegistros {
            get {
                return this.CantTotalRegistrosField;
            }
            set {
                if ((this.CantTotalRegistrosField.Equals(value) != true)) {
                    this.CantTotalRegistrosField = value;
                    this.RaisePropertyChanged("CantTotalRegistros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SYS_SGI.Presentation.ServiceSecurity.InfoMovs InfoMovs {
            get {
                return this.InfoMovsField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoMovsField, value) != true)) {
                    this.InfoMovsField = value;
                    this.RaisePropertyChanged("InfoMovs");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Opcion", Namespace="http://schemas.datacontract.org/2004/07/SYS_SECURITY.Domain.Implementation.Entiti" +
        "es.SEG")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SYS_SGI.Presentation.ServiceSecurity.OpcionLogic))]
    public partial class Opcion : SYS_SGI.Presentation.ServiceSecurity.Audity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CodigoModuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CodigoOpcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ControladorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GlyphiconField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long OpcionPadreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CodigoModulo {
            get {
                return this.CodigoModuloField;
            }
            set {
                if ((this.CodigoModuloField.Equals(value) != true)) {
                    this.CodigoModuloField = value;
                    this.RaisePropertyChanged("CodigoModulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CodigoOpcion {
            get {
                return this.CodigoOpcionField;
            }
            set {
                if ((this.CodigoOpcionField.Equals(value) != true)) {
                    this.CodigoOpcionField = value;
                    this.RaisePropertyChanged("CodigoOpcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Controlador {
            get {
                return this.ControladorField;
            }
            set {
                if ((object.ReferenceEquals(this.ControladorField, value) != true)) {
                    this.ControladorField = value;
                    this.RaisePropertyChanged("Controlador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Glyphicon {
            get {
                return this.GlyphiconField;
            }
            set {
                if ((object.ReferenceEquals(this.GlyphiconField, value) != true)) {
                    this.GlyphiconField = value;
                    this.RaisePropertyChanged("Glyphicon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Metodo {
            get {
                return this.MetodoField;
            }
            set {
                if ((object.ReferenceEquals(this.MetodoField, value) != true)) {
                    this.MetodoField = value;
                    this.RaisePropertyChanged("Metodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long OpcionPadre {
            get {
                return this.OpcionPadreField;
            }
            set {
                if ((this.OpcionPadreField.Equals(value) != true)) {
                    this.OpcionPadreField = value;
                    this.RaisePropertyChanged("OpcionPadre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Orden {
            get {
                return this.OrdenField;
            }
            set {
                if ((this.OrdenField.Equals(value) != true)) {
                    this.OrdenField = value;
                    this.RaisePropertyChanged("Orden");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoMovs", Namespace="http://schemas.datacontract.org/2004/07/SYS_SECURITY.Domain.Implementation.Entiti" +
        "es.BASE")]
    [System.SerializableAttribute()]
    public partial class InfoMovs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ACCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int I_TOTAL_RECORDSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TotalRegistrosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ACCION {
            get {
                return this.ACCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.ACCIONField, value) != true)) {
                    this.ACCIONField = value;
                    this.RaisePropertyChanged("ACCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int I_TOTAL_RECORDS {
            get {
                return this.I_TOTAL_RECORDSField;
            }
            set {
                if ((this.I_TOTAL_RECORDSField.Equals(value) != true)) {
                    this.I_TOTAL_RECORDSField = value;
                    this.RaisePropertyChanged("I_TOTAL_RECORDS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TotalRegistros {
            get {
                return this.TotalRegistrosField;
            }
            set {
                if ((this.TotalRegistrosField.Equals(value) != true)) {
                    this.TotalRegistrosField = value;
                    this.RaisePropertyChanged("TotalRegistros");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppResponse", Namespace="http://schemas.datacontract.org/2004/07/SYS_SECURITY.Domain.Implementation.Entiti" +
        "es.BASE")]
    [System.SerializableAttribute()]
    public partial class AppResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSecurity.IAcceso")]
    public interface IAcceso {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcceso/ListarPermisos_x_Usuario_Sistema", ReplyAction="http://tempuri.org/IAcceso/ListarPermisos_x_Usuario_SistemaResponse")]
        SYS_SGI.Presentation.ServiceSecurity.OpcionLogic[] ListarPermisos_x_Usuario_Sistema(string usuario, int codigoSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcceso/ListarPermisos_x_Usuario_Sistema", ReplyAction="http://tempuri.org/IAcceso/ListarPermisos_x_Usuario_SistemaResponse")]
        System.Threading.Tasks.Task<SYS_SGI.Presentation.ServiceSecurity.OpcionLogic[]> ListarPermisos_x_Usuario_SistemaAsync(string usuario, int codigoSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcceso/ListarUsuarios_Login", ReplyAction="http://tempuri.org/IAcceso/ListarUsuarios_LoginResponse")]
        SYS_SGI.Presentation.ServiceSecurity.UsuariosLogic ListarUsuarios_Login(int codigoUsuario, int codigoSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcceso/ListarUsuarios_Login", ReplyAction="http://tempuri.org/IAcceso/ListarUsuarios_LoginResponse")]
        System.Threading.Tasks.Task<SYS_SGI.Presentation.ServiceSecurity.UsuariosLogic> ListarUsuarios_LoginAsync(int codigoUsuario, int codigoSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcceso/Usuario_x_Sistema", ReplyAction="http://tempuri.org/IAcceso/Usuario_x_SistemaResponse")]
        SYS_SGI.Presentation.ServiceSecurity.OpcionLogic[] Usuario_x_Sistema(string usuario, int codigo_sistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcceso/Usuario_x_Sistema", ReplyAction="http://tempuri.org/IAcceso/Usuario_x_SistemaResponse")]
        System.Threading.Tasks.Task<SYS_SGI.Presentation.ServiceSecurity.OpcionLogic[]> Usuario_x_SistemaAsync(string usuario, int codigo_sistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcceso/Sistema_x_Token", ReplyAction="http://tempuri.org/IAcceso/Sistema_x_TokenResponse")]
        SYS_SGI.Presentation.ServiceSecurity.SistemaLogic Sistema_x_Token(string token, int codigo_usuario, int codigoSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcceso/Sistema_x_Token", ReplyAction="http://tempuri.org/IAcceso/Sistema_x_TokenResponse")]
        System.Threading.Tasks.Task<SYS_SGI.Presentation.ServiceSecurity.SistemaLogic> Sistema_x_TokenAsync(string token, int codigo_usuario, int codigoSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcceso/ObtenerEmpresa", ReplyAction="http://tempuri.org/IAcceso/ObtenerEmpresaResponse")]
        SYS_SGI.Presentation.ServiceSecurity.EmpresaLogic ObtenerEmpresa(int CodigoEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcceso/ObtenerEmpresa", ReplyAction="http://tempuri.org/IAcceso/ObtenerEmpresaResponse")]
        System.Threading.Tasks.Task<SYS_SGI.Presentation.ServiceSecurity.EmpresaLogic> ObtenerEmpresaAsync(int CodigoEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcceso/Login", ReplyAction="http://tempuri.org/IAcceso/LoginResponse")]
        SYS_SGI.Presentation.ServiceSecurity.UsuariosLogic Login(string user, string contrasena, int codigoSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcceso/Login", ReplyAction="http://tempuri.org/IAcceso/LoginResponse")]
        System.Threading.Tasks.Task<SYS_SGI.Presentation.ServiceSecurity.UsuariosLogic> LoginAsync(string user, string contrasena, int codigoSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcceso/CambiarContrasena", ReplyAction="http://tempuri.org/IAcceso/CambiarContrasenaResponse")]
        SYS_SGI.Presentation.ServiceSecurity.AppResponse CambiarContrasena(int codigoUsuario, string contrasenaNueva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcceso/CambiarContrasena", ReplyAction="http://tempuri.org/IAcceso/CambiarContrasenaResponse")]
        System.Threading.Tasks.Task<SYS_SGI.Presentation.ServiceSecurity.AppResponse> CambiarContrasenaAsync(int codigoUsuario, string contrasenaNueva);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccesoChannel : SYS_SGI.Presentation.ServiceSecurity.IAcceso, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccesoClient : System.ServiceModel.ClientBase<SYS_SGI.Presentation.ServiceSecurity.IAcceso>, SYS_SGI.Presentation.ServiceSecurity.IAcceso {
        
        public AccesoClient() {
        }
        
        public AccesoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccesoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccesoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccesoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SYS_SGI.Presentation.ServiceSecurity.OpcionLogic[] ListarPermisos_x_Usuario_Sistema(string usuario, int codigoSistema) {
            return base.Channel.ListarPermisos_x_Usuario_Sistema(usuario, codigoSistema);
        }
        
        public System.Threading.Tasks.Task<SYS_SGI.Presentation.ServiceSecurity.OpcionLogic[]> ListarPermisos_x_Usuario_SistemaAsync(string usuario, int codigoSistema) {
            return base.Channel.ListarPermisos_x_Usuario_SistemaAsync(usuario, codigoSistema);
        }
        
        public SYS_SGI.Presentation.ServiceSecurity.UsuariosLogic ListarUsuarios_Login(int codigoUsuario, int codigoSistema) {
            return base.Channel.ListarUsuarios_Login(codigoUsuario, codigoSistema);
        }
        
        public System.Threading.Tasks.Task<SYS_SGI.Presentation.ServiceSecurity.UsuariosLogic> ListarUsuarios_LoginAsync(int codigoUsuario, int codigoSistema) {
            return base.Channel.ListarUsuarios_LoginAsync(codigoUsuario, codigoSistema);
        }
        
        public SYS_SGI.Presentation.ServiceSecurity.OpcionLogic[] Usuario_x_Sistema(string usuario, int codigo_sistema) {
            return base.Channel.Usuario_x_Sistema(usuario, codigo_sistema);
        }
        
        public System.Threading.Tasks.Task<SYS_SGI.Presentation.ServiceSecurity.OpcionLogic[]> Usuario_x_SistemaAsync(string usuario, int codigo_sistema) {
            return base.Channel.Usuario_x_SistemaAsync(usuario, codigo_sistema);
        }
        
        public SYS_SGI.Presentation.ServiceSecurity.SistemaLogic Sistema_x_Token(string token, int codigo_usuario, int codigoSistema) {
            return base.Channel.Sistema_x_Token(token, codigo_usuario, codigoSistema);
        }
        
        public System.Threading.Tasks.Task<SYS_SGI.Presentation.ServiceSecurity.SistemaLogic> Sistema_x_TokenAsync(string token, int codigo_usuario, int codigoSistema) {
            return base.Channel.Sistema_x_TokenAsync(token, codigo_usuario, codigoSistema);
        }
        
        public SYS_SGI.Presentation.ServiceSecurity.EmpresaLogic ObtenerEmpresa(int CodigoEmpresa) {
            return base.Channel.ObtenerEmpresa(CodigoEmpresa);
        }
        
        public System.Threading.Tasks.Task<SYS_SGI.Presentation.ServiceSecurity.EmpresaLogic> ObtenerEmpresaAsync(int CodigoEmpresa) {
            return base.Channel.ObtenerEmpresaAsync(CodigoEmpresa);
        }
        
        public SYS_SGI.Presentation.ServiceSecurity.UsuariosLogic Login(string user, string contrasena, int codigoSistema) {
            return base.Channel.Login(user, contrasena, codigoSistema);
        }
        
        public System.Threading.Tasks.Task<SYS_SGI.Presentation.ServiceSecurity.UsuariosLogic> LoginAsync(string user, string contrasena, int codigoSistema) {
            return base.Channel.LoginAsync(user, contrasena, codigoSistema);
        }
        
        public SYS_SGI.Presentation.ServiceSecurity.AppResponse CambiarContrasena(int codigoUsuario, string contrasenaNueva) {
            return base.Channel.CambiarContrasena(codigoUsuario, contrasenaNueva);
        }
        
        public System.Threading.Tasks.Task<SYS_SGI.Presentation.ServiceSecurity.AppResponse> CambiarContrasenaAsync(int codigoUsuario, string contrasenaNueva) {
            return base.Channel.CambiarContrasenaAsync(codigoUsuario, contrasenaNueva);
        }
    }
}
